version: '3'

services:
  app1:
    build: .
    container_name: app1
    command: node app1.js
    ports:
      - "3000:3000"

  app2:
    build: .
    container_name: app2
    command: node app2.js
    ports:
      - "3001:3001"
